# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
